### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by weltonsantana2026**

### CODE REVIEW

**Comment by weltonsantana2026** [comment]
> _No description provided._

**Comment by ItsVixano** [comment]
Vr00 binod 🙏

**Comment by shuend** [comment]
> Vr00 binod 🙏

wot is binod mean

**Comment by RyuujiX** [comment]
Bruh, Not all Screen panel will support some Hz even it has Same Panel Model

**Comment by raghavt20** [comment]
> > Vr00 binod 🙏
> 
> wot is binod mean

binod

**Pull request closed without merging**
